name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Test
    runs-on: takumi-runner
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Build binary via Docker
        run: make build-docker

      - name: Upload binary
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: bloodhound-binary
          path: target/docker/bloodhound
          retention-days: 1
